### ISSUE TITLE
New Need: get the newest version number from the App Store of my IOS App?

### ISSUE THREAD

**Issue by NikiLee2016** [fiber-god/react-native-app-link#12]
I used "react-native-app-link" in my app, it works great! And now I have a new need: Check upgrade from App Store server rather than from my own server. Can you support it?

**Comment by NikiLee2016** [comment]
If you are not interested in that, could tell me how to do that? Because I am not familiar with IOS development. Thx a lot!

**Comment by FiberJW** [comment]
Sorry I totally missed this. I don't believe that that is within the scope of this project, nor is it related to it. Good luck with your project!
