### ISSUE TITLE
there is no example for guidance

### ISSUE THREAD

**Issue by shukla12manish** [fiber-god/react-native-app-link#14]
I made a simple button in my app named "Open Whatsapp". On press of this button i want to open whatsapp if installed it will directly open it in my phone else it will redirect me to Playstore. But i am not able to implement this. Kindly help. 

What will be the url in below code and where shoid i get all these details.

```
AppLink.maybeOpenURL(url, { appName, appStoreId, appStoreLocale, playStoreId }).then(() => {
  // do stuff
})
.catch((err) => {
  // handle error
});
```

**Comment by sagarhudge** [comment]
@alleyhector @shukla12manish @FiberJW @sonaye  @brentvatne @PeterChauYEG @
Any update on this issue or can anyone have a sample for this?

**Comment by sagarhudge** [comment]
> I made a simple button in my app named "Open Whatsapp". On press of this button i want to open whatsapp if installed it will directly open it in my phone else it will redirect me to Playstore. But i am not able to implement this. Kindly help.
> 
> What will be the url in below code and where shoid i get all these details.
> 
> ```
> AppLink.maybeOpenURL(url, { appName, appStoreId, appStoreLocale, playStoreId }).then(() => {
>   // do stuff
> })
> .catch((err) => {
>   // handle error
> });
> ```

any update on this I am facing the same issue

**Comment by FiberJW** [comment]
The url would be the `whatsapp://...` url linking to whatever content you want within the WhatsApp app. https://faq.whatsapp.com/en/iphone/23559013

**Comment by sagarhudge** [comment]
@FiberJW @brentvatne @alleyhector @PeterChauYEG @sonaye 
I am implementing **react-native-app-link**  in my project but I am facing issue in the implementation I have a list of applications on the press of a specific button it should either **open the app or redirect to play store or app store.** 

**I do not have any deep-link URL for this app** is there any way to achieve this?

**Example for my app: IOS and Android**

Package name: com.medlife.customerApp 
name:  MedlifePlay 

iOS: package name: medlife-all-things-healthapp
 id: 1078091111
App store name :Medlife

**If possible please provide demo example for this library**
