### ISSUE TITLE
Example ? 

### ISSUE THREAD

**Issue by kri-yor** [fiber-god/react-native-app-link#5]
Can you provide an example in code ?
I can't seem to make it work. 

Thank you !

**Comment by FiberJW** [comment]
https://github.com/fiber-god/pul/blob/master/components/Event.js#L349

**Comment by kri-yor** [comment]
Still the same. I can't figure out how to use this in any project. I just get error Can't find variable: uri

Fixed it. uri needs to be 'uri'

**Comment by jalexandremoreira** [comment]
How do you find app ids?

**Comment by ThukuWakogi** [comment]
@jalexandremoreira 
in a url like `https://apps.apple.com/id/app/whatsapp-messenger/id310633997`
The numbers after id
