### ISSUE TITLE
It always open either PlayStore

### ISSUE THREAD

**Issue by smithaitufe** [fiber-god/react-native-app-link#6]
This is code in my app always opens Instagram in the Play Store.
```js
AppLink.maybeOpenURL("com.whatsapp", { appName: "Whatsapp", appStoreId: "", playStoreId: "com.whatsapp" })
```
Please what could I be doing wrong

**Comment by FiberJW** [comment]
What you probably want, is an Intent launcher like Expo's IntentLauncherAndroid API => https://docs.expo.io/versions/latest/sdk/intent-launcher.html 

Using that will open the Whatsapp Android activity without attempting to access a specific route/action.

The first parameter, `url` is for [deep linking](https://en.wikipedia.org/wiki/Mobile_deep_linking) into an app. To do that, you'd need a [Whatsapp specific url](https://faq.whatsapp.com/en/android/28000012) like `whatsapp://send?text=helloworld`.

I have no idea why Instagram would be opening, by the way.

I hope I helped a bit!

**Comment by smithaitufe** [comment]
@fiber-god Sorry. I meant to say whatsapp not instagram. 

### Custom URL
I tried *whatsapp://app* but it did not work

With respect to the Expo IntentLauncherAndroid, what is required is ACTION_VIEW, but as it stands, Expo does not have it.

Thanks for your help

**Comment by FiberJW** [comment]
Expo's intent actions are actually just pure strings, so even if it doesn't have something you need already defined, you can still use it by passing in the intent string you need. https://github.com/expo/expo-sdk/blob/master/src/IntentLauncherAndroid.js#L81

**Comment by FiberJW** [comment]
See the constant value here: https://developer.android.com/reference/android/content/Intent.html#ACTION_VIEW

**Comment by FiberJW** [comment]
If you want, you could submit a PR adding that ACTION_VIEW intent here: https://github.com/expo/expo-sdk/blob/master/src/IntentLauncherAndroid.js
https://github.com/expo/expo-sdk/pulls

**Comment by smithaitufe** [comment]
@fiber-god I tried the ACTION_VIEW, 

here is the code I used
```js
await IntentLauncherAndroid.startActivityAsync(IntentLauncherAndroid.ACTION_VIEW)
```
and this is exception I got
```
 [Unhandled promise rejection: Error: Specified activity was empty]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:123:42 in createErrorFromErrorData
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:80:57 in <unknown>
- ... 5 more stack frames from framework internals
```

**Comment by smithaitufe** [comment]
In this [page](https://github.com/expo/expo-sdk/blob/master/src/IntentLauncherAndroid.js#L81), ACTION_VIEW is missing

**Comment by FiberJW** [comment]
Here's what you want, I can confirm it works: 
```js
AppLink.maybeOpenURL('whatsapp://send', {
      appName: 'WhatsApp',
      appStoreId: '',
      playStoreId: 'com.whatsapp',
    });
```
Snack Link: https://snack.expo.io/SJpWmBmwG, just run on your android phone

**Comment by FiberJW** [comment]
@smithaitufe does this solve your issue?

**Comment by smithaitufe** [comment]
Nope. I will close it tonight once I find a solution and I will report back

**Comment by FiberJW** [comment]
Maybe you simply don't have Whatsapp installed on your device? The code I proposed seems to fulfill your needs, opening Whatsapp right?
