### ISSUE TITLE
it always opening playstore link

### ISSUE THREAD

**Issue by shaikhussian** [fiber-god/react-native-app-link#7]
Hi,

I installed this module for app linking,

My requirement:

In my react-native app i want to open the other native app.
If the native app is installed then it need to open the app.
if app is not installed then it need to open in playstore.

for that i used the code like this

code:

```
AppLink.maybeOpenURL('https://play.google.com/store/apps/details?id=com.ubercab.driver&hl=en',
 { appName:'Uber Driver',playStoreId:'com.ubercab.driver' }).then(() => {
    // do stuff
})
    .catch((err) => {
        // handle error
    });
```

as per the module Readme it need to open app if app already installed, In my device app is already installed but it is still showing the playstore link,

Can you please give me some suggestions that how can i achieve it. Any help much useful

**Comment by FiberJW** [comment]
The first parameter isn't the URL to the play store app like how you're calling it. It's a [mobile deep link](https://en.wikipedia.org/wiki/Mobile_deep_linking) like `twitter://...`. You have to find out if Uber's Driver app supports deep links and use their format in the first parameter
