### ISSUE TITLE
Itunes app store link not working

### ISSUE THREAD

**Issue by alleyhector** [fiber-god/react-native-app-link#8]
Finally got your module installed after a bunch of errors (not sure what did it in the end but I've re-installed almost everything) and had it working fine when I did have the app installed but was getting an error when I tried using it when I did not have the app installed.

Firstly, here's my code example:

```
import {
    maybeOpenURL
} from 'react-native-app-link';
```
and then down in the render:
```
<Text style={{color: 'red'}}
                onPress={() => maybeOpenURL("lyft://", { 
                    appName: "Lyft", 
                    appStoreId: "529379082", 
                    playStoreId: "me.lyft.android" })}>
            Lyft
</Text>
```
(Sidenote: your documentation actually says to use `import AppLink from 'react-native-app-link';`  and then `AppLink.maybeOpenURL...` but I could not get that working so I opened up the file in the node module directly and just grabbed what I needed).

So the error I got on my simulator appeared here:
<img width="317" alt="screen shot 2018-05-29 at 3 13 33 pm" src="https://user-images.githubusercontent.com/1653653/40688952-f5aac944-6354-11e8-8c73-db1d12c14ff7.png">

And running expo directly on my phone:
![rn-app-error](https://user-images.githubusercontent.com/1653653/40689181-f9125894-6355-11e8-9ded-8f03da533e14.jpg)

So I looked closer could only guess that the link you're using might need updating? You have:
`https://itunes.apple.com/${locale}/app/${appStoreId}`
when I replaced it with
`https://itunes.apple.com/${locale}/app/${appName}/id${appStoreId}`
it worked on my iphone, directing me to the app store when I didn't have the app installed. 

Unfortunately, I still get the error in the simulator, which I prefer to use. Not sure if there's anything you can do about that but it would be great.

**Comment by FiberJW** [comment]
Yep, it looks like the iTunes link may need to be updated. It won't work in your simulator simply because it doesn't give you access to the app store, hence the error. If you could submit a PR with the link update, that would be amazing!

**Comment by alleyhector** [comment]
Sounds good. Pull request made.

Is there an explanation for using `import AppLink from 'react-native-app-link';` rather than `import maybeOpenURL from 'react-native-app-link'; ` or does this just need to be updated in the readme?

**Comment by FiberJW** [comment]
I exported the API with named exports and also wrapped in a default object. You should be able to both import the function by name: `import { maybeOpenURL } from 'react-native-app-link'` and import the default object and access the functions by their property name: `import AppLink from 'react-native-app-link'; AppLink.maybeOpenURL...`.

Are you using a special language like Flow or TypeScript that could be compiling the exports differently? This is the first time anyone has brought up an issue with the way they imported the module

**Comment by alleyhector** [comment]
Looks like it's working ok now, must have been conflated with other issues I was having. Thanks.
